### ISSUE TITLE
Clarify how path selection is done for protection engine packets

### ISSUE THREAD

**Issue by gloinul** [gloinul/draft-westerlund-tsvwg-sctp-crypto-chunk#5]
Michael Tüxen review noted that we does not discuss how path selection for the protection engine created packets work. This also comes with an additional issue that needs to be clarified. Namely how path failures are handled. So if no SCTP packets are sent but protection engine sends packet then the SCTP stack is not aware of these packets and do not notice that they are not acknowledged by the peer protection engine. Some mechanism will be needed here to handle this case.

**Comment by teiclap** [comment]
Actually SCTP protocol helps here.
SCTP stack does continuously supervise the paths either with traffic or with path probing using HB/HB-ACK.
The selection of the current path is done at SCTP thus messages belonging to protection engine will exploit that path.
We are not including CRYPTO chunks in the account for SACK assuming that the encryption engine itself is able dealing with data loss and can wait until SCTP does probe the path.
A solution here may be simple, that is we do nothing so that we have a risk that the protection engine runs into timeout before SCTP switches to the alternative paths in case of multihoming. Such case would possibly happen when protection engine has internal data to be sent and the Upper Layer Application has no traffic for a long time.
Alternative is complex and requires a though interaction between protection engine and SCTP, it may be that in case of SCTP is idle then protection engine forces HB chunks to be sent. 
A simpler solution is to tune HB properly, for instance by sending an HB every 2 seconds or so. This we can provide as recommendation for the specific protection engine. In DTLS I'd see a good choice to have HB at 2 seconds rate.

**Comment by teiclap** [comment]
Addressed in branch issue5

**Comment by gloinul** [comment]
Resolved #12
